name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js 12.14.0
      uses: actions/setup-node@v3
      with:
        node-version: 12.14.0
        cache: 'npm'
    - name: Install dependencies
      run: npm ci

    - name: Build Angular app
      run: npm run build --if-present

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy API
      run: |
        cd /api
        npm install
        nodemon

    - name: Deploy APP
      run: |
        cd /app
        npm install
        npm run start

