name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 12.14.0
        uses: actions/setup-node@v3
        with:
          node-version: 12.14.0
          cache: 'npm'

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.7'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: |
          npm install node-sass@4.12.0
          npm install

      - name: Set up Environment Variables
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_USER_PASS=${{ secrets.DB_USER_PASS }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check current directory
        run: |
          pwd
          ls -la

      - name: Navigate to project directory
        run: cd $GITHUB_WORKSPACE

      - name: Deploy API
        run: |
          npm --prefix $GITHUB_WORKSPACE run start:api

      - name: Deploy Angular App
        run: |
          npm run build:app
